### PR TITLE
Fix JSONFormat to output valid JSON strings

### LINKED ISSUE #31: JSONFormat outputs non-JSON on some non-printable characters
**Describe the bug**
`JSONFormat` is expected to output JSON regardless of the input data, but outputs non-JSON on some special characters; `\x00`, `\a`, `\v`, `\U0001FBFF`.

**Environments**
- Version: [1.6.1](https://github.com/cybozu-go/log/releases/tag/v1.6.1)
- OS: macOS 12.2.1
- Go: go1.17.8 darwin/amd64

**To Reproduce**
Run following code.
```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/cybozu-go/log"
)

func main() {
	var err error
	l := log.NewLogger()
	f := log.JSONFormat{Utsname: "test"}
	t := time.Now()

	buf := make([]byte, 0, 256)
	buf, err = f.Format(buf, l, t, log.LvDebug, "test", map[string]interface{}{
		"x": "\x00\a\v\U0001FBFF",
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", err)
		os.Exit(1)
	}
	fmt.Printf("%s\n", buf)

	var data interface{}
	err = json.Unmarshal(buf, &data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", err)
		os.Exit(1)
	}
	fmt.Printf("%v\n", data)
}
```

Get following output.
```
{"topic":"main","logged_at":"2022-03-15T06:39:16.059075Z","severity":"debug","utsname":"test","message":"test","x":"\x00\a\v\U0001fbff"}

invalid character 'x' in string escape code
exit status 1
```

**Expected behavior**
`JSONFormat` emits valid JSON even if the input data contains non-printable characters, and the output is safely decoded back to the data.

**Additional context**
Currently this formatter uses [`strconv.AppendQuote`](https://pkg.go.dev/strconv#AppendQuote) to encode string values. This method is intended to output Go string literal representation, which allows wider range of character representation than JSON. For example, `"\x00\a\v\U0001FBFF"` is a valid Go string literal, but its quoted value `"\"\\x00\\a\\v\\U0001fbff\""` is not a valid JSON.

### PR DESCRIPTION
**Pull request by itchyny**
This PR fixes JSONFormat to output valid JSON strings regardless of the fields data, resolves #31.

### CODE REVIEW

File: json.go [hunk 1]
```diff
@@ -316,3 +307,53 @@ func appendFloat(buf []byte, v float64, bitSize int) []byte {
 		return strconv.AppendFloat(buf, v, 'f', -1, bitSize)
 	}
 }
+
+// Ref: encodeState#string in encoding/json.
```
Comment (itchyny) [inline json.go:311]: This implementation might look kind of a horrible idea causing code duplicates, but I don't think there's a better way to solve the original issue with no allocation overhead. I hope there is `json.AppendMarshal([]byte, v any) ([]byte, error)` in `encoding/json` package.

Comment (itchyny) [reply json.go:311]: Another solution is to create a writer wrapping a `bytes.Buffer` to use `json.Encoder.Encode`, just like I'm proposing in different package (https://github.com/hokaccha/go-prettyjson/pull/21/files#diff-2fc4cc94d53b67bb93f26e56ef7ee4b2344b0b20970b9b971cbf418f4fc31818R233-R244), but this is actually slower than directly appending to `[]byte` for maximum performance like this log package.

File: json.go [hunk 2]
```diff
@@ -190,15 +189,11 @@ func appendJSON(buf []byte, v interface{}) ([]byte, error) {
 		}
 		return appendFloat(buf, t, 64), nil
 	case string:
-		if !utf8.ValidString(t) {
-			// the next line replaces invalid characters.
-			t = strings.ToValidUTF8(t, string(utf8.RuneError))
-		}
 		// escaped length = 2*len(t) + 2 double quotes
 		if cap(buf) < (len(t)*2 + 2) {
```
Comment (morimoto-cybozu) [inline json.go:193]: We also need to update the estimation of the buffer usage to `(len(t)*6 + 2)`.

We should not append data to `buf` when `buf` needs to be extended for the extra data.
Instead, we should return `(nil, ErrTooLarge)`.
https://github.com/cybozu-go/log/blob/v1.6.1/formatter.go#L16

`(len(t)*6 + 2)` would be an overestimation in most cases.
Will this change seriously increase the risk of errors in logging?
I suppose "No."
The size of `buf` is 1 MiB and it would be sufficient even for the new estimation.
https://github.com/cybozu-go/log/blob/v1.6.1/constants.go#L45

File: json.go [hunk 3]
```diff
@@ -223,18 +218,14 @@ func appendJSON(buf []byte, v interface{}) ([]byte, error) {
 		if cap(buf) < (len(s)*2 + 2) {
```
Comment (morimoto-cybozu) [inline json.go:218]: ditto

File: json.go [hunk 4]
```diff
@@ -223,18 +218,14 @@ func appendJSON(buf []byte, v interface{}) ([]byte, error) {
...
-		return strconv.AppendQuote(buf, string(s)), nil
+		return appendString(buf, string(s)), nil
 	case error:
 		s := t.Error()
-		if !utf8.ValidString(s) {
-			// the next line replaces invalid characters.
-			s = strings.ToValidUTF8(s, string(utf8.RuneError))
-		}
 		// escaped length = 2*len(s) + 2 double quotes
 		if cap(buf) < (len(s)*2 + 2) {
```
Comment (morimoto-cybozu) [inline json.go:225]: ditto

**Review by morimoto-cybozu — CHANGES_REQUESTED** [review]

File: json.go (hunk 2 above)
Comment (itchyny) [reply json.go:193]: All these capacity checks are broken since implemented, see #32.

Comment (morimoto-cybozu) [reply json.go:193]: WTH! Let's fix estimations in another PR.

**Review by morimoto-cybozu — APPROVED** [review]
